# Generated by Django 2.2.12 on 2021-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('channel', models.CharField(max_length=100)),
                ('published_on', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
